##Business Problem
Stakeholder: Real Estate Agency

Business Problem:
The real estate agency wants to optimize their sales strategy by providing insights to homeowners on how they can increase the value of their properties. Specifically, they want to offer advice on home renovations that could potentially boost the estimated value of homes in the northwestern county.

Objective:
To develop a predictive model using multiple linear regression analysis that can estimate the impact of different home renovation features such as bedrooms, bathrooms, living space, etc. on the sale price of houses in the northwestern county. This model will enable the real estate agency to provide tailored advice to homeowners regarding which renovations are likely to yield the highest return on investment in terms of increasing property value.

This business problem aligns with the provided dataset as it includes various features related to the characteristics of houses and their sale prices, allowing us to perform regression analysis to identify the factors influencing property values in the region.

In [1]:
#importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

In [2]:
df = pd.read_csv('kc_house_data.csv')
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,10/13/2014,221900.0,3,1.00,1180,5650,1.0,NaN,NONE,...,7 Average,1180,0.0,1955,0.0,98178,47.5112,-122.257,1340,5650
1,6414100192,12/9/2014,538000.0,3,2.25,2570,7242,2.0,NO,NONE,...,7 Average,2170,400.0,1951,1991.0,98125,47.7210,-122.319,1690,7639
2,5631500400,2/25/2015,180000.0,2,1.00,770,10000,1.0,NO,NONE,...,6 Low Average,770,0.0,1933,NaN,98028,47.7379,-122.233,2720,8062
3,2487200875,12/9/2014,604000.0,4,3.00,1960,5000,1.0,NO,NONE,...,7 Average,1050,910.0,1965,0.0,98136,47.5208,-122.393,1360,5000
4,1954400510,2/18/2015,510000.0,3,2.00,1680,8080,1.0,NO,NONE,...,8 Good,1680,0.0,1987,0.0,98074,47.6168,-122.045,1800,7503

In [3]:
df.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,sqft_above,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.159700e+04,2.159700e+04,21597.000000,21597.000000,21597.000000,2.159700e+04,21597.000000,21597.000000,21597.000000,17755.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000
mean,4.580474e+09,5.402966e+05,3.373200,2.115826,2080.321850,1.509941e+04,1.494096,1788.596842,1970.999676,83.636778,98077.951845,47.560093,-122.213982,1986.620318,12758.283512
std,2.876736e+09,3.673681e+05,0.926299,0.768984,918.106125,4.141264e+04,0.539683,827.759761,29.375234,399.946414,53.513072,0.138552,0.140724,685.230472,27274.441950
min,1.000102e+06,7.800000e+04,1.000000,0.500000,370.000000,5.200000e+02,1.000000,370.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.220000e+05,3.000000,1.750000,1430.000000,5.040000e+03,1.000000,1190.000000,1951.000000,0.000000,98033.000000,47.471100,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,1560.000000,1975.000000,0.000000,98065.000000,47.571800,-122.231000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068500e+04,2.000000,2210.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,9410.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [4]:
correlation = df.corr()['price'].sort_values(ascending=False)
correlation

<ipython-input-4-1ec7ea11b09a>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation = df.corr()['price'].sort_values(ascending=False)

price            1.000000
sqft_living      0.701917
sqft_above       0.605368
sqft_living15    0.585241
bathrooms        0.525906
bedrooms         0.308787
lat              0.306692
floors           0.256804
yr_renovated     0.129599
sqft_lot         0.089876
sqft_lot15       0.082845
yr_built         0.053953
long             0.022036
id              -0.016772
zipcode         -0.053402
Name: price, dtype: float64

##Choosing the columns to use in the analysis
We can use the columns with the highest correlation<br>
These are: sqft_living, sqft_above, sqft_living15, bathrooms,bedrooms

In [5]:
df_subset = df[['sqft_living','sqft_above','sqft_living15','bathrooms','bedrooms']]
df_subset.head()

   sqft_living  sqft_above  sqft_living15  bathrooms  bedrooms
0         1180        1180           1340       1.00         3
1         2570        2170           1690       2.25         3
2          770         770           2720       1.00         2
3         1960        1050           1360       3.00         4
4         1680        1680           1800       2.00         3

##Data Preparation

In [6]:
print("Dataset info:")
print(df_subset.info())
print(" ") # printing a whitespace line
print("Dataset describe:")
print(df_subset.describe())

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sqft_living    21597 non-null  int64
 1   sqft_above     21597 non-null  int64
 2   sqft_living15  21597 non-null  int64
 3   bathrooms      21597 non-null  float64
 4   bedrooms       21597 non-null  int64
dtypes: float64(1), int64(4)
memory usage: 843.8 KB
None

Dataset describe:
        sqft_living    sqft_above  sqft_living15     bathrooms      bedrooms
count  21597.000000  21597.000000   21597.000000  21597.000000  21597.000000
mean    2080.321850   1788.596842    1986.620318      2.115826      3.373200
std      918.106125    827.759761     685.230472      0.768984      0.926299
min      370.000000    370.000000     399.000000      0.500000      1.000000
25%     1430.000000   1190.000000    1490.000000      1.750000      3.000000
50%     1910.000000   1560.000000    1840.000000      2.250000      3.000000
75%     2550.000000   2210.000000    2360.000000      2.500000      4.000000
max    13540.000000   9410.000000    6210.000000      8.000000     33.000000

##Modelling